[2024-02-20T20:34:11.874+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: api_dag.save_posts manual__2024-02-20T20:34:09.844029+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
